# fly.toml app configuration file generated for bashcatbackend on 2023-11-01T08:00:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bashcatbackend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
